const QuestionActions = {
    SAVE_QUESTION: "SAVE_QUESTION",
    UPDATE_QUESTION: "UPDATE_QUESTION",
    DELETE_QUESTION: "DELETE_QUESTION",
    GET_QUESTION: "GET_QUESTION",
    GET_ALL_QUESTIONS: "GET_ALL_QUESTIONS",
    QUESTIONS_COUNT: "QUESTIONS_COUNT"
}
export default QuestionActions;