const TopicActions = {
    SAVE_TOPIC: "SAVE_TOPIC",
    UPDATE_TOPIC: "UPDATE_TOPIC",
    DELETE_TOPIC: "DELETE_TOPIC",
    GET_TOPIC: "GET_TOPIC",
    GET_ALL_TOPICS: "GET_ALL_TOPICS",
    TOPIC_NAMES: "TOPIC_NAMES",
}
export default TopicActions;