const UserActions = {
    SAVE_USER: "SAVE_USER",
    UPDATE_USER: "UPDATE_USER",
    DELETE_USER: "DELETE_USER",
    GET_USER: "GET_USER",
    GET_ALL_USERS: "GET_ALL_USERS",
    ADD_LOGIN_USER_DATA:"ADD_LOGIN_USER_DATA",
    GET_LOGIN_USER_DATA:"GET_LOGIN_USER_DATA",
}
export default UserActions;